'use client';

import { useMemo } from 'react';
import { SandpackProvider, SandpackPreview } from '@codesandbox/sandpack-react';
import type { BuilderFiles } from '@/types/code';

interface CodePreviewProps {
    files: BuilderFiles;
    reloadKey?: number;
}

/**
 * Tailwind is delivered via the Play CDN script tag — no PostCSS compilation
 * pipeline needed. The Node.js tailwindcss/postcss/autoprefixer packages crash
 * Sandpack's in-browser Node runtime (exit code 1) because they rely on the
 * real Node fs/path modules that are only partially shimmed.
 */
const DEFAULT_LAYOUT = `
export const metadata = {
  title: 'Preview',
  description: 'Generated by SouvikAI',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Tailwind Play CDN — no build step required */}
        <script src="https://cdn.tailwindcss.com" />
        <style>{
          \`body { font-family: system-ui, -apple-system, BlinkMacSystemFont,
            'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell,
            'Open Sans', 'Helvetica Neue', sans-serif; }\`
        }</style>
      </head>
      <body>{children}</body>
    </html>
  )
}
`;

export function CodePreview({ files, reloadKey = 0 }: CodePreviewProps) {
    const sandpackFiles = useMemo(() => {
        const result: Record<string, string> = {
            // Only inject a layout when the agent hasn't written one.
            '/app/layout.tsx': DEFAULT_LAYOUT,
        };
        for (const [path, content] of Object.entries(files)) {
            result[`/${path}`] = content;
        }
        return result;
    }, [files]);

    return (
        <div className="flex-1 min-h-0 bg-background" key={reloadKey}>
            <SandpackProvider
                template="nextjs"
                files={sandpackFiles}
                customSetup={{
                    dependencies: {
                        // UI / animation helpers the agent commonly imports.
                        'lucide-react': 'latest',
                        'framer-motion': 'latest',
                        'clsx': 'latest',
                        'tailwind-merge': 'latest',
                        '@radix-ui/react-icons': 'latest',
                        '@radix-ui/react-slot': 'latest',
                        // NOTE: tailwindcss / postcss / autoprefixer are
                        // intentionally omitted — they are Node.js-only and
                        // crash Sandpack's in-browser runtime. Tailwind is
                        // loaded via Play CDN in the layout instead.
                    },
                }}
            >
                <div className="h-full w-full [&_.sp-layout]:h-full [&_.sp-layout]:w-full [&_.sp-preview]:h-full [&_.sp-preview-iframe]:h-full [&_.sp-preview-iframe]:w-full">
                    <SandpackPreview
                        showOpenInCodeSandbox={false}
                        showRefreshButton={false}
                    />
                </div>
            </SandpackProvider>
        </div>
    );
}
